- name: installing redis
  hosts: redis
  become: yes
  tasks:
    - name: install remi release
      ansible.builtin.dnf: # check pacakge will work not
        name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
        state: present
        disable_gpg_check: true
    - name: enable redis
      ansible.builtin.command: dnf module enable redis:remi-6.2 -y

    - name: install remi release
      ansible.builtin.dnf: # check pacakge will work not
        name: redis
        state: present
    - name: start and enable redis
      ansible.builtin.service:
        name: redis
        state: started
    - name: replace string
      ansible.builtin.replace:
        path: /etc/redis/redis.conf
        regexp: "127.0.0.1"
        replace: "0.0.0.0"
    - name: start and enable redis
      ansible.builtin.service:
        name: redis
        state: restarted
