- name: installing user application
  hosts: web
  become: yes
  tasks:
    - name: installing nginx
      ansible.builtin.dnf:
        name: nginx
        state: present
    - name: start the service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
    - name: create directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent
    - name: create directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory
    - name: download application
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/web.zip
        dest: /tmp
    - name: unzipping file
      ansible.builtin.unarchive:
        src: /tmp/web.zip
        dest: /usr/share/nginx/html
        remote_src: yes
    - name: copy roboshop.conf file
      ansible.builtin.copy:
        path: roboshop.conf
        dest: /etc/nginx/default.d
    - name: start the service
      ansible.builtin.service:
        name: nginx
        state: restarted
